{% set name = "gemspa-spt" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gemspa-spt-{{ version }}.tar.gz
  sha256: 61c63c673e3b4d13558e8c4e4a20a56d49d1810d1c358cfe629c9aef379cf604

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=43.0.0
  run:
    - numpy
    - pandas
    - python >=3.8
    - scipy

test:
  imports:
    - gemspa_spt
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/gemspa-spt
  summary: A package for analysis of single particle tracking experiments
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/liamholtlab/gemspa-spt

extra:
  recipe-maintainers:
    - goanpeca
    - snkeegan
